// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stock_interface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion5

// DefaultClient is the client API for Default service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DefaultClient interface {
	Login(ctx context.Context, in *LoginRequest) (*LoginReply, error)
	ListOperation(ctx context.Context, in *ListOperationRequest) (*ListOperationReply, error)
	UpsetOperation(ctx context.Context, in *UpsetOperationRequest) (*UpsetOperationReply, error)
	DeleteOperation(ctx context.Context, in *DeleteOperationRequest) (*DeleteOperationReply, error)
}

type defaultClient struct {
	cc interface {
		Invoke(ctx context.Context, method string, args, reply proto.Message) error
	}
}

func NewDefaultClient(cc interface {
	Invoke(ctx context.Context, method string, args, reply proto.Message) error
}) DefaultClient {
	return &defaultClient{cc}
}

func (c *defaultClient) Login(ctx context.Context, in *LoginRequest) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/stock.Default/Login", in, out)
	return out, err
}

func (c *defaultClient) ListOperation(ctx context.Context, in *ListOperationRequest) (*ListOperationReply, error) {
	out := new(ListOperationReply)
	err := c.cc.Invoke(ctx, "/stock.Default/ListOperation", in, out)
	return out, err
}

func (c *defaultClient) UpsetOperation(ctx context.Context, in *UpsetOperationRequest) (*UpsetOperationReply, error) {
	out := new(UpsetOperationReply)
	err := c.cc.Invoke(ctx, "/stock.Default/UpsetOperation", in, out)
	return out, err
}

func (c *defaultClient) DeleteOperation(ctx context.Context, in *DeleteOperationRequest) (*DeleteOperationReply, error) {
	out := new(DeleteOperationReply)
	err := c.cc.Invoke(ctx, "/stock.Default/DeleteOperation", in, out)
	return out, err
}

// DefaultServer is the server API for Default service.
type DefaultServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	ListOperation(context.Context, *ListOperationRequest) (*ListOperationReply, error)
	UpsetOperation(context.Context, *UpsetOperationRequest) (*UpsetOperationReply, error)
	DeleteOperation(context.Context, *DeleteOperationRequest) (*DeleteOperationReply, error)
}

// UnimplementedDefaultServer can be embedded to have forward compatible implementations.
type UnimplementedDefaultServer struct {
}

func (*UnimplementedDefaultServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedDefaultServer) ListOperation(context.Context, *ListOperationRequest) (*ListOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperation not implemented")
}
func (*UnimplementedDefaultServer) UpsetOperation(context.Context, *UpsetOperationRequest) (*UpsetOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsetOperation not implemented")
}
func (*UnimplementedDefaultServer) DeleteOperation(context.Context, *DeleteOperationRequest) (*DeleteOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOperation not implemented")
}

func RegisterDefaultServer(s interface {
	RegisterService(sd *grpc.ServiceDesc, ss interface{})
}, srv DefaultServer) {
	s.RegisterService(&_Default_serviceDesc, srv)
}

func _Default_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.Default/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Default_ListOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServer).ListOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.Default/ListOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServer).ListOperation(ctx, req.(*ListOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Default_UpsetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServer).UpsetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.Default/UpsetOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServer).UpsetOperation(ctx, req.(*UpsetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Default_DeleteOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServer).DeleteOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.Default/DeleteOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServer).DeleteOperation(ctx, req.(*DeleteOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Default_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stock.Default",
	HandlerType: (*DefaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Default_Login_Handler,
		},
		{
			MethodName: "ListOperation",
			Handler:    _Default_ListOperation_Handler,
		},
		{
			MethodName: "UpsetOperation",
			Handler:    _Default_UpsetOperation_Handler,
		},
		{
			MethodName: "DeleteOperation",
			Handler:    _Default_DeleteOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/service.proto",
}
