// Code generated by protoc-gen-go-api. DO NOT EDIT.

package proto

import (
	context "context"
	common_interface "github.com/any-lyu/interface_golang/golang/common_interface"
	messagebus_request_to_load_test_interface "github.com/any-lyu/interface_golang/golang/messagebus_request_to_load_test_interface"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
)

// Server is the rpc server interface, rpc.Server implements this interface
type Server interface {
	RegisterService(sd *grpc.ServiceDesc, ss interface{})
}

// Invoker is the method invoke interface, rpc.Client implements this interface
type Invoker interface {
	Invoke(ctx context.Context, method string, args, reply proto.Message) error
}

// InvokerFactory is the factory that makes Invoker
type InvokerFactory interface {
	MakeInvoker(host string) Invoker
}

// MethodOptionFuncs contains methods for processing method option
type MethodOptionFuncs interface {
	// OfficeNetworkOnly only accepts requests from office and rejects other requests
	OfficeNetworkOnly(context.Context) error
	// MustAuthenticated rejects invalid authentication requests
	MustAuthenticated(context.Context) error
	// MustHavePermission checks whether the user has a specific permission, if not, then reject the request
	MustHavePermission(context.Context, common_interface.Permission) error
	// HandleRequestToLoadTest handles messagebus_request_to_load_test_interface.Message, generally sent to the message bus.
	HandleRequestToLoadTest(context.Context, *messagebus_request_to_load_test_interface.Message) error
}
