// Code generated by protoc-gen-go-api. DO NOT EDIT.

package internal

import (
	proto "github.com/any-lyu/interface_golang/golang_api/proto"
)

// RegisterServiceFunc is function that register service to Server
//
//  env: qa|pre|prd
type RegisterServiceFunc func(env string, _ proto.Server, _ proto.InvokerFactory, _ proto.MethodOptionFuncs)

// RegisterServiceFuncArray is used to register RegisterServiceFunc
var RegisterServiceFuncArray = make([]RegisterServiceFunc, 0, 1024)
